name: wiki_art
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  infinite_scroll_pagination: ^1.1.1
  cached_network_image: ^2.3.2+1
  google_fonts: ^1.1.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  flutter_bloc: ^6.0.5
  flutter_svg: ^0.19.0
  eva_icons_flutter: ^2.0.1
  fluro: ^1.6.3
  equatable: ^1.2.5
  shimmer: ^1.1.1
  flutter_cache_manager: ^1.4.2
  extended_image: ^1.1.2
  overlay_dialog: ^0.0.3


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/artists.json
    - assets/json/test.json


